version: '3.8'

services:
  apache:
    build: ./apache
    ports:
      - "8080:80"
    volumes:
      - ./apache/index.php:/var/www/html/index.php
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reg1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
